const AT = {
  //people
  ADD_PEOPLE: 'ADD_PEOPLE',
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_IS_SEARCHING: 'SET_IS_SEARCHING',
  SET_NEXT_PEOPLE_PAGE_ID: 'SET_NEXT_PEOPLE_PAGE_ID',
  //planets
  ADD_PLANETS: 'ADD_PLANETS',
  SET_NEXT_PLANETS_PAGE_ID: 'SET_NEXT_PLANETS_PAGE_ID',
  //species
  ADD_SPECIES: 'ADD_SPECIES',
  SET_NEXT_SPECIES_PAGE_ID: 'SET_NEXT_SPECIES_PAGE_ID',
  //films
  ADD_FILMS: 'ADD_FILMS',
  SET_NEXT_FILMS_PAGE_ID: 'SET_NEXT_FILMS_PAGE_ID',
  //search
  ADD_SEARCHABLE_PEOPLE: 'ADD_SEARCHABLE_PEOPLE',
  SET_IS_LOADING_SEARCH: 'SET_IS_LOADING_SEARCH',
  SET_IS_FOUND: 'SET_IS_FOUND',
};

export default AT;
